import React from 'react'

import '@/styles/base.css'

import { Figtree } from 'next/font/google'

import { Main } from '@/ui/main'
import { Navigation } from '@/ui/navigation'
import { Header } from '@/components/header'
import { Toaster } from '@/ui/toast'
import { getCurrentUser } from '@/lib/session'

const figtree = Figtree({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const user = await getCurrentUser()
	return (
		<html lang="en" className={figtree.className}>
			<body className="bg-base-100">
				<div id="app">
					<Header user={user} />
					<div className="h-full relative">
						<Navigation />
						<Main>{children}</Main>
					</div>
					<Toaster position="bottom-center" />
				</div>
				{/* {children} */}
				{/* <div className="h-[30000px]  bg-orange-300"></div> */}
			</body>
		</html>
	)
}
