import '@/styles/base.css'

import { Inter as FontSans } from 'next/font/google'

import { Help } from '@/components/help'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { Toaster } from '@/ui/toast'
import { cn } from '@/lib/utils'
import { MainNav } from '@/components/nav'
import { Footer, Navbar } from '@/components/layouts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-inter',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={cn('bg-white font-sans text-slate-900 antialiased', fontSans.variable)}
    >
      <body className="@container/body">
        <Navbar />
        <section className="min-h-[calc(100%-64px)] bg-slate-100">{children}</section>
        {/* <MainNav /> */}
        <Help />
        <Toaster position="bottom-center" />
        <TailwindIndicator />
        {/* <Footer /> */}
      </body>
    </html>
  )
}
